// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zfamxsklzwcnkxkhiwbk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpmYW14c2tsendjbmt4a2hpd2JrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0MTMwOTQsImV4cCI6MjA3Mzk4OTA5NH0.cmM1gH8ohLoCydI_ZBw7Pbr9zT_jkkUFb5E0ZNmWUDE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});